# Generated by Django 4.1.2 on 2022-10-18 15:07

import ckeditor_uploader.fields
from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Титле')),
                ('title_h2', models.CharField(max_length=250, verbose_name='Титле-2')),
                ('title_h3', models.CharField(max_length=250, verbose_name='Титле-3')),
                ('poster', models.ImageField(upload_to='', verbose_name='Постер')),
                ('image_right', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('desc_h2', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание-2')),
                ('desc_h3', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание-3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles',
                'ordering': ('-id',),
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
