# Generated by Django 4.1.2 on 2022-10-19 14:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='desc_h2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='desc_h3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_right',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_h2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_h3',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(upload_to='articles/poster', verbose_name='Постер'),
        ),
    ]
